### ISSUE TITLE
net5.0

### ISSUE THREAD

**Issue by mikes-gh** [soundaranbu/RazorTemplating#9] opened 2020-10-18 23:27 UTC
Great to see this common use case packaged and tested and professionally built.
Do you have plans for a net5.0 version

**Comment by SoundarRBT** [comment] 2020-10-19 05:36
Hi @mikes-gh , Thanks for recognizing this library and YES! I do have plans for .NET 5 which is currently in RC2.
I'm planning to release on the day of release of live version of .NET 5 which is expected to be in November. 
Keep supporting :) Thanks!

**Comment by soundaranbu** [comment] 2020-10-19 05:38
Hi @mikes-gh , Thanks for recognizing this library and YES! I do have plans for .NET 5 which is currently in RC2.
I'm planning to release on the day of release of live version of .NET 5 which is expected to be in November.
Keep supporting :) Thanks!

**Comment by litan1106** [comment] 2020-11-10 18:11
.net5 released today

**Comment by soundaranbu** [comment] 2020-11-11 09:19
Yeah @litan1106 , I'm on it.

**Comment by litan1106** [comment] 2020-11-11 16:03
> Yeah @litan1106 , I'm on it.

Awesome, I think you have the best razor template library.

**Comment by soundaranbu** [comment] 2020-11-13 07:49
Thanks!. As far as I've tested this library(v1.2.1) against net5.0, it works as intended. So the existing users can continue using the latest version(v1.2.1) for .NET 5 as well until any issues are found and fixed.

**Comment by litan1106** [comment] 2020-11-13 15:55
> Thanks!. As far as I've tested this library(v1.2.1) against net5.0, it works as intended. So the existing users can continue using the latest version(v1.2.1) for .NET 5 as well until any issues are found and fixed.

Sounds good. I will remove the .net core 3.0 tests and add .net 5 tests

**Comment by soundaranbu** [comment] 2020-11-14 12:12
Thanks for your contribution. I'll check & merge the changes

**Comment by soundaranbu** [comment] 2020-11-17 18:21
New version released with .NET 5 support and other enhancements.  :tada:
Please find the release notes here: https://github.com/soundaranbu/RazorTemplating/releases/tag/v1.3.0

Available in NuGet. Give it a spin. Keep supporting :)

**Closed by soundaranbu** 2020-11-17 18:21 UTC
Labels: question

**Comment by litan1106** [comment] 2020-11-17 19:00
> New version released with .NET 5 support and other enhancements. 🎉
> Please find the release notes here: https://github.com/soundaranbu/RazorTemplating/releases/tag/v1.3.0
> 
> Available in NuGet. Give it a spin. Keep supporting :)

Thank you for the hard work
