### ISSUE TITLE
Unable to resolve System.Diagnostics.DiagnosticSource 

### ISSUE THREAD

**Issue by arnithin-rda** [soundaranbu/RazorTemplating#33] opened 2021-11-17 13:54 UTC
Hi,

I am using azure functions and when I try to call RazorTemplateEngine.RenderAsync(), I am getting below error. 
 **Microsoft.Extensions.DependencyInjection: Unable to resolve service for type 'System.Diagnostics.DiagnosticSource' while attempting to activate 'Microsoft.AspNetCore.Mvc.Razor.RazorPageActivator'.** 

My Azure functions csproj looks like this,
`<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>v3</AzureFunctionsVersion>
    <UserSecretsId></UserSecretsId>
	<_FunctionsExtensionTargetFramework>netstandard2.0</_FunctionsExtensionTargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="3.1.10" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.1" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.OpenApi" Version="0.9.0-preview" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="3.1.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="3.1.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Http" Version="3.1.20" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Razor.Templating.Core" Version="1.6.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
	<PackageReference Include="System.ServiceModel.Duplex" Version="4.5.3" />
	<PackageReference Include="System.ServiceModel.Http" Version="4.5.3" />
	<PackageReference Include="System.ServiceModel.NetTcp" Version="4.5.3" />
	<PackageReference Include="System.ServiceModel.Security" Version="4.5.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Assurant.AntiqueAutoUnderwriter.API.DataAccess\Assurant.AntiqueAutoUnderwriter.API.DataAccess.csproj" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Assurant.AntiqueAutoUnderwriter.API.Common\Assurant.AntiqueAutoUnderwriter.API.Common.csproj" />
    <ProjectReference Include="..\Assurant.AntiqueAutoUnderwriter.API.Contracts\Assurant.AntiqueAutoUnderwriter.API.Contracts.csproj" />
    <ProjectReference Include="..\Assurant.AntiqueAutoUnderwriter.API.DataAccess\Assurant.AntiqueAutoUnderwriter.API.DataAccess.csproj" />
    <ProjectReference Include="..\Assurant.AntiqueAutoUnderwriter.API.ViewsTemplates\Assurant.AntiqueAutoUnderwriter.API.ViewsTemplates.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <WCFMetadata Include="Connected Services" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Connected Services\" />
  </ItemGroup>
	
</Project>
`

My Razor class library file name is 'Assurant.AntiqueAutoUnderwriter.API.ViewsTemplates.csproj' which has been referenced

Kindly let me know if I am missing something as I am struggling to make it work in our app.

Note: I created a new sample functions app and when I tried to use the Razor.Templating.core package (1.6.0), it is working. But the above mentioned code is our existing functions app project and we need to render view in this project.

Please find the below screenshot:

![image](https://user-images.githubusercontent.com/94539772/142213565-25c6fff2-4f33-4d21-a67e-092188220488.png)

**Comment by soundaranbu** [comment] 2021-11-20 15:40
Hi @arnithin-rda , Since this issue occurs only on a particular project of yours, I would like you to kindly upload a sample repo to reproduce the issue. 
Otherwise, you can try comparing the working one vs non-working one & eliminate the differences one by one 

I suspect these dependencies `<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" /> <PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="3.1.10" /> `

**Comment by soundaranbu** [comment] 2022-01-23 10:09
Closing this issue as there's no update. Please feel free to re-open if required. Thanks!

**Closed by soundaranbu** 2022-01-23 10:09 UTC
